version: '3'
services:
  server1:
    build:
      context: .
    command: uvicorn main:app1 --host 0.0.0.0 --port 8000
    ports:
      - 8000

  server2:
    build:
      context: .
    command: uvicorn main:app2 --host 0.0.0.0 --port 8080
    ports:
      - 8080

  nginx:
    image: nginx:latest
    command: sh -c "mkdir -p /var/nginx/cache && nginx -g 'daemon off;'"
    
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8888:8888